version: '3.1'

services:

  db:
    image: postgres
    container_name: movie-recommendation-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: movie-recommendation-redis
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

volumes:
  pgdata: